name: chat_app_client
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  web_socket_channel: ^3.0.1
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  socket_io_client: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.2.1
  timeago: ^3.7.0
  intl: ^0.18.1
  
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  build: ^2.4.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logokg.png"

flutter:
  assets:
    - .env
    - assets/images/logokg.png
  
  uses-material-design: true

